locastyle:
  themes:
    aqua: colorAqua
    blue: colorBlue
    green: colorGreen
    orange: colorOrange
    purple: colorPurple
    wine: colorWine
    navy_blue: colorNavyBlue
    light_blue: colorLightBlue
